Main Documentation
==================
Tim Yates
2014-02-04
:jbake-type: page
:jbake-tags: documentation, manual
:jbake-status: published

https://github.com/timyates/groovy-stream[groovy-stream] is a library to simplify
the generation of lazy Iterators across a mutitude of input data types, and the
construction of finite Lazy Generators from a collection of inputs.

== Table of Contents
. xref:getting-started[Getting Started]
.. xref:using-maven[Using Maven]
.. xref:using-grab[Using `Grab`]
.. xref:downloading[Downloading]
.. xref:dependencies[Dependencies]
. xref:quick-example[Quick Example]
.. xref:lazy-generators[Lazy Generators]
. xref:anatomy-of-a-stream[Anatomy of a Stream]
.. xref:inputs[Inputs]
.. xref:filters[Filters]
.. xref:mappings[Mappings]
.. xref:inspectors[Inspectors]
.. xref:crossing-the-streams[Crossing the Streams]

[[getting-started]]
== Getting started

[[using-maven]]
=== Using Maven

[source,xml]
----
<dependency>
    <groupId>com.bloidonia</groupId>
    <artifactId>groovy-stream</artifactId>
    <version>0.7.0</version>
</dependency>
----

[[using-gradle]]
=== Using Gradle

[source,groovy]
----
compile "com.bloidonia:groovy-stream:0.7.0"
----

[[using-grab]]
=== Using Grab

[source,groovy]
----
@Grab( "com.bloidonia:groovy-stream:0.7.0" )
import groovy.stream.*
----

[[downloading]]
=== Downloading

Jar files can be directly downloaded from the `Files` tab on Bintray by
https://bintray.com/timyates/groovy-stream/groovy-stream[following this link],
and clicking on the version you require.

[[dependencies]]
=== Dependencies

The only runtime dependency of `groovy-stream` is Groovy.  I track the current
Groovy version, but it should work with all versions from 2.0+.

[[quick-example]]
== Quick Example

As a simple example, lets create a `Stream` representing all positive integers:

[source,groovy]
----
include::../../src/test/groovy/asciidoc/BriefExamples.groovy[tags=part_one,indent=0]
----

We can then create a `Stream` that is fed from integers and returns a `Stream` of squares:

[source,groovy]
----
include::../../src/test/groovy/asciidoc/BriefExamples.groovy[tags=part_two,indent=0]
----

And we can then take the first 5 elements from this stream with:

[source,groovy]
----
include::../../src/test/groovy/asciidoc/BriefExamples.groovy[tags=part_three,indent=0]
----

It is only at the point where we call `collect()` that the original `integers`
stream is executed five times, to produce five values which are squared in turn
and passed to the result `first5`.

[[lazy-generators]]
=== Lazy Generators

We can use the Stream to mimic the behaviour of a list comprehension. Lets say we want to do the following:

===============================
For all values of `x` from 1 to 5 and all values of `y` from 1 to 3;
return `x + 1` if `( x + y ) % ( x + 2 ) == 0`
===============================

[source,groovy]
----
include::../../src/test/groovy/asciidoc/BriefExamples.groovy[tags=faux_comprehension,indent=0]
----

[[anatomy-of-a-stream]]
== Anatomy of a Stream

Streams can be thought of as a chain of Iterators.  Each iterator in the chain
takes the previous iterator's output as it's input, performs some task to it and
passes this to the next Iterator *on request*.

The head iterator of the chain is wrapped in a `Stream` class which allows simple
creation of new iterators in the chain.

[[inputs]]
=== Inputs

To create a `Stream` class you can either use one of the many static `from` methods:

[source,java]
----
    public static <K,V> Stream<Map<K,V>>  from( Map<K,? extends Iterable<V>> map )
    public static <T>   Stream<T>         from( Stream<T> stream                 )
    public static <T>   Stream<T>         from( Iterable<T> iterable             )
    public static <T>   Stream<T>         from( Iterator<T> iterator             )
    public static       Stream<String>    from( BufferedReader reader            )
    public static <T>   Stream<T>         from( Closure<T> closure               )
    public static <T>   Stream<T>         from( T[] array                        )
    public static       Stream<Byte>      from( byte[] array                     )
    public static       Stream<Character> from( char[] array                     )
    public static       Stream<Short>     from( short[] array                    )
    public static       Stream<Integer>   from( int[] array                      )
    public static       Stream<Long>      from( long[] array                     )
    public static       Stream<Float>     from( float[] array                    )
    public static       Stream<Double>    from( double[] array                   )
    public static       Stream<Boolean>   from( boolean[] array                  )
----

Or, you can make use of the Groovy Extension class which adds the `toStream()`
method to:

- `Closure`
- `Iterator`
- `Iterable<T>`
- `BufferedReader`
- `Map<K,? extends Iterable<V>>`
- `Object[]`
- `byte[]`
- `char[]`
- `short[]`
- `int[]`
- `long[]`
- `float[]`
- `double[]`
- `boolean[]`

Once you have this single Iterator `Stream`, you can then perform different operations
to create a new filtered, transformed, limited or conjoined `Stream`

[[filters]]
=== Filters


[[mappings]]
=== Mappings
[[inspectors]]
=== Inspectors
[[crossing-the-streams]]
=== Crossing the Streams
